### PR TITLE
Changed LICENSE from MIT to Apache 2.0.

### PR DESCRIPTION
**Pull request by nmccrory**
## The Problem:
drud/docker.mysql-local was under the MIT License.
## The Fix:
Update LICENSE to the Apache 2.0 License.

## Related Issue Link(s):
drud/general/[#128](https://github.com/drud/general/issues/128#issuecomment-320350151)

### CODE REVIEW

**Comment by beeradb** [comment]
These are built on the official MySQL docker images, which are [licensed under the GPL](https://github.com/docker-library/mysql/blob/0590e4efd2b31ec794383f084d419dea9bc752c4/LICENSE). We'll need to determine whether we can provide our own license for our customizations or not.

**Comment by rickmanelius** [comment]
This one has a GPL2 upstream, which we identified as being some problematic. Leaving as a "needs decision" as the first test case on how to deal with exceptions.

**Comment by rickmanelius** [comment]
A few items/questions:

1. We're moving to MariaDB for hosting. If we do this and we decide to get parity over on ddev, this becomes moot because we can deprecate this image. Thoughts, @beeradb or @rfay?
2. If we're sticking with this container, I'm having difficulty tracing the license back to the upstream Oracle license that @cyberswat refers to above. Could someone take 5 and walk me through that?

**Comment by rickmanelius** [comment]
Related: this might offer a faster way to check/validate these moving forward https://github.com/drud/general/issues/132.

**Comment by beeradb** [comment]
I'm fairly positive the [MariaDB container](https://hub.docker.com/_/mariadb/) has feature parity with the default MySQL container. 

I'm guessing it's not a whole lot of effort to switch over to it, and is probably for the best in the long run.

**Comment by rickmanelius** [comment]
My vote then is to swap the containers and render this PR moot. I would imagine @rfay would be the one with the best visibility on the change over timing of that in a new issue that we can call this one blocked until that's tasked and merged.

**Comment by rickmanelius** [comment]
Closing this and filing a new issue to convert to the mariadb container and essentially deprecate this repo.

**Pull request closed without merging**
